import { FormSectionConfig, INDUSTRY_OPTIONS, LANGUAGE_OPTIONS, TIMEZONE_OPTIONS, PERSONALITY_OPTIONS, TONE_OPTIONS, FORMALITY_OPTIONS, DEPARTMENT_OPTIONS, ROLE_OPTIONS, SUMMARY_STRUCTURE_OPTIONS, FORMAT_OPTIONS, REQUIRED_FIELD_OPTIONS, CRM_OPTIONS } from "@/lib/types/assistant-config-simple";

export const AI_ASSISTANT_FORM_CONFIG: FormSectionConfig[] = [
    {
        title: "Company Information",
        description: "Basic company details and operational settings",
        fields: [
            {
                name: "companyName",
                label: "Company Name",
                type: "text",
                placeholder: "Enter your company name",
                description: "The official name of your company",
                required: true,
            },
            {
                name: "industryType",
                label: "Industry Type",
                type: "select",
                placeholder: "Select your industry",
                description: "Your primary business industry",
                options: INDUSTRY_OPTIONS,
                required: true,
            },
            {
                name: "primaryLanguage",
                label: "Primary Language",
                type: "select",
                placeholder: "Select primary language",
                description: "Main language for AI interactions",
                options: LANGUAGE_OPTIONS,
                required: true,
            },
            {
                name: "timezone",
                label: "Timezone",
                type: "select",
                placeholder: "Select your timezone",
                description: "Your company's operating timezone",
                options: TIMEZONE_OPTIONS,
                required: true,
            },
            {
                name: "operationalHoursStart",
                label: "Operational Start Time",
                type: "time",
                description: "When your business day begins",
                required: true,
            },
            {
                name: "operationalHoursEnd",
                label: "Operational End Time",
                type: "time",
                description: "When your business day ends",
                required: true,
            },
        ],
    },
    {
        title: "Voice Agent Identity",
        description: "Configure your AI assistant's personality and behavior",
        fields: [
            {
                name: "agentName",
                label: "AI Agent Name",
                type: "text",
                placeholder: "e.g., Ava, Alex, Sarah",
                description: "A friendly name for your AI assistant",
                required: true,
            },
            {
                name: "personality",
                label: "Preferred Agent Personality",
                type: "select",
                placeholder: "Select personality type",
                description: "How the AI should behave during interactions",
                options: PERSONALITY_OPTIONS,
                required: true,
            },
            {
                name: "toneOfVoice",
                label: "Tone of Voice",
                type: "select",
                placeholder: "Select tone of voice",
                description: "The vocal tone the AI should use",
                options: TONE_OPTIONS,
                required: true,
            },
            {
                name: "formalityLevel",
                label: "Formality Level",
                type: "radio",
                description: "How formal the AI should be in conversations",
                options: FORMALITY_OPTIONS,
                required: true,
            },
        ],
    },
    {
        title: "Department Structure",
        description: "Define departments and call preferences",
        fields: [
            {
                name: "departments",
                label: "List of Departments",
                type: "multiselect",
                description: "Select all departments in your organization",
                options: DEPARTMENT_OPTIONS,
                required: true,
            },
            {
                name: "dailyCallDepartments",
                label: "Departments Receiving Daily Calls",
                type: "multiselect",
                description: "Which departments should receive daily check-in calls?",
                options: DEPARTMENT_OPTIONS,
            },
            {
                name: "departmentSpecificQuestions",
                label: "Department-Specific Questions",
                type: "textarea",
                placeholder: "Enter any specific questions that should be asked for certain departments...",
                description: "Specify any department-specific questions or requirements",
            },
        ],
    },
    {
        title: "Call Workflow Setup",
        description: "Set up calling hierarchy and recipients",
        fields: [
            {
                name: "rolesToContact",
                label: "Roles to Be Contacted",
                type: "multiselect",
                description: "Select the roles that should be contacted during workflows",
                options: ROLE_OPTIONS,
                required: true,
            },
            {
                name: "callOrder",
                label: "Call Order",
                type: "multiselect",
                description: "Order in which roles should be contacted (select in order)",
                options: ROLE_OPTIONS,
                required: true,
            },
            {
                name: "reportRecipients",
                label: "Consolidated Report Recipients",
                type: "multiselect",
                description: "Who should receive the consolidated reports? (e.g., Director, COO)",
                options: ROLE_OPTIONS,
                required: true,
            },
        ],
    },
    {
        title: "Question Set Preferences",
        description: "Configure questions and compliance checks",
        fields: [
            {
                name: "useDefaultQuestionSet",
                label: "Use Default Question Set",
                type: "checkbox",
                description: "Use our pre-configured question set for daily check-ins and reporting",
            },
            {
                name: "complianceChecks",
                label: "Critical Compliance or Process Checks",
                type: "textarea",
                placeholder: "List any critical compliance requirements, safety checks, or mandatory processes...",
                description: "Include any regulatory or safety requirements that must be checked",
            },
            {
                name: "businessTerms",
                label: "Business Terms, KPIs, and Jargon",
                type: "textarea",
                placeholder: "List key terms, KPIs, or industry-specific jargon (e.g., 'NCR', 'Work Orders', 'Shift Handover')...",
                description: "Help the AI understand your business terminology and key metrics",
            },
        ],
    },
    {
        title: "Prompt Structure Adjustments",
        description: "Customize AI behavior and protocols (Optional)",
        fields: [
            {
                name: "customSystemPrompt",
                label: "Custom System Prompt Additions",
                type: "textarea",
                placeholder: "Add any specific instructions for how the AI should behave, respond, or handle conversations...",
                description: "Optional overrides or additions to the base AI prompt",
            },
            {
                name: "sensitiveTopics",
                label: "Sensitive Topics to Avoid",
                type: "textarea",
                placeholder: "List topics the AI should avoid discussing (e.g., personal matters, politics, financial details)...",
                description: "Topics the AI should not engage with during calls",
            },
            {
                name: "escalationProtocols",
                label: "Escalation Protocols",
                type: "textarea",
                placeholder: "Define what the AI should do when serious issues are reported (e.g., safety incidents, emergencies, compliance violations)...",
                description: "Instructions for handling serious situations that require immediate escalation",
            },
        ],
    },
    {
        title: "Summary Requirements",
        description: "Define report structure and output formatting",
        fields: [
            {
                name: "summaryStructure",
                label: "Summary Structure",
                type: "select",
                placeholder: "Select summary structure",
                description: "How should the AI structure the summary content?",
                options: SUMMARY_STRUCTURE_OPTIONS,
                required: true,
            },
        ],
    },
    {
        title: "Output Formatting Preferences",
        description: "Choose formats, required fields, and validation",
        fields: [
            {
                name: "preferredFormat",
                label: "Preferred Output Format",
                type: "select",
                placeholder: "Select output format",
                description: "Format for data export and integration",
                options: FORMAT_OPTIONS,
                required: true,
            },
            {
                name: "requiredFields",
                label: "Required Fields",
                type: "multiselect",
                description: "Select which fields should always be extracted and included in reports",
                options: REQUIRED_FIELD_OPTIONS,
            },
            {
                name: "dataValidation",
                label: "Data Validation Rules",
                type: "textarea",
                placeholder: "Specify validation rules, constraints, or format requirements (e.g., date formats, time units, numeric ranges)...",
                description: "Define any data validation or formatting constraints",
            },
        ],
    },
    {
        title: "Cost and Duration Calculation",
        description: "Configure cost tracking and duration calculation",
        fields: [
            {
                name: "calculateDurations",
                label: "Calculate Call Durations",
                type: "checkbox",
                description: "Track and report the duration of each AI voice call",
            },
            {
                name: "includeCosting",
                label: "Include Cost Calculations",
                type: "checkbox",
                description: "Calculate and report the cost of AI voice calls for budgeting",
            },
            {
                name: "costPerMinute",
                label: "Cost Per Minute ($)",
                type: "number",
                placeholder: "0.00",
                description: "The cost charged per minute of AI voice call (e.g., $0.05)",
                step: "0.01",
                min: 0,
            },
        ],
    },
    {
        title: "Integration Settings",
        description: "Connect to external systems (Optional)",
        fields: [
            {
                name: "crmSystem",
                label: "CRM or Data System",
                type: "select",
                placeholder: "Select your CRM or data system",
                description: "Where should the AI assistant data be sent?",
                options: CRM_OPTIONS,
            },
            {
                name: "webhookUrl",
                label: "Webhook or API Endpoint URL",
                type: "text",
                placeholder: "https://api.example.com/webhook or https://hooks.zapier.com/...",
                description: "The URL where data should be sent via HTTP POST",
            },
            {
                name: "apiKeys",
                label: "Authentication Details",
                type: "textarea",
                placeholder: "API Key: your_api_key_here\nBearer Token: your_token_here\nAdditional headers or authentication details...",
                description: "API keys, tokens, or other authentication details (stored securely)",
            },
        ],
    },
];
